# Generated by Django 2.0.9 on 2019-01-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='link',
        ),
    ]
